### ISSUE TITLE
关于数据集标注

### ISSUE THREAD

**Issue by LYXLYXlyv** [zhaoyunpeng57/BUAA-UESD33#2]
请问你们是如何对这么多张图片进行标注的

**Comment by zhaoyunpeng57** [comment]
在UE4中生成卫星原图。手动设置各部件颜色为红、绿、蓝等颜色，生成同原图视角的标签图，提取标签图rgb像素值，即为标签。
部分图像手动标注。

**Comment by LYXLYXlyv** [comment]
好的，谢谢
